export const TOOL_HELP: Record<string, readonly [string, string, string]> = {
  privacy: ['Choose Privacy Review, Redact Image or Remove Metadata, then select a photo or screenshot.', 'Review the whole image. English text suggestions can miss sensitive details, including QR codes and faces.', 'Export a new copy. Your original stays unchanged and processing stays on your device.'],
  privacy_scan: ['Choose a screenshot or photo to scan for possible sensitive English text.', 'Review each suggestion and add covers for anything missed. Check QR codes and other visible details manually.', 'Export and inspect the new image before sharing. Your original stays unchanged.'],
  privacy_redact: ['Choose a photo or screenshot, then cover details you want to hide.', 'Review the whole image and adjust the selected areas before exporting.', 'Export a new image with the covers applied to its pixels. Your original stays unchanged.'],
  privacy_metadata: ['Choose a photo or screenshot.', 'Create a fresh image without its source metadata. Visible text, faces and QR codes are still present.', 'Review the copy before sharing. Use Redact Image to cover visible details when needed.'],
  info: ['Choose a PDF or open Details from the reader.', 'Review page count, dimensions, PDF version and encryption.', 'Scroll to see document properties such as title and author.'],
  duplicate: ['Enter page numbers or ranges, such as 1, 3-5.', 'Each selected page is copied immediately after its original.', 'Name the result, then create and save your PDF.'],
  insert: ['Choose an insertion position. Use 0 for the beginning.', 'Insert a blank page, or choose a PDF to insert all its pages.', 'Name the result, then save or share it.'],
  compress: ['Choose Max quality, Balanced or Smallest.', 'Estimate the size. Balanced and Smallest create image-based pages; text and forms become static.', 'Compare the actual result size, then save or share it.'],
  to_image: ['Choose page numbers or ranges, up to 100 pages.', 'Choose JPG or PNG and a quality level.', 'Name your export. Each page becomes a separate image you can save or share.'],
  highlight: ['Choose Area or Brush, then drag across a passage. Style & colour controls ink and thickness.', 'Use Previous and Next to mark other pages. Undo and Redo step through your marks. Pinch with two fingers to zoom.', 'Choose Save or Save as new, then check your PDF.'],
  draw: ['Draw directly on the page.', 'Choose a color and stroke width. Use Undo if needed.', 'Save your PDF and check the result.'],
  shapes: ['Choose Rectangle or Ellipse, then drag on the page.', 'Choose a color and stroke width. Undo removes the last shape.', 'Save your PDF and check the result.'],
  sign: ['Draw your signature where it belongs on the page.', 'Use Undo to retry. This is a visual signature, not certificate-based signing.', 'Save your PDF, check it, then save or share.'],
  add_image: ['Choose an image to place on the current PDF page.', 'Drag the image to move it and its corner handles to resize it. Select another page to add another image.', 'Choose Save or Save as new. Your image is embedded in the PDF.'],
  watermark: ['Choose pages and enter a short English label.', 'A translucent label is centered on each selected page.', 'Create and open the result before saving or sharing.'],
  numbers: ['Choose pages and a starting number.', 'Selected pages receive consecutive numbers at the bottom.', 'Create and review the result.'],
  protect: ['Enter matching passwords with 6–64 English letters, numbers or symbols.', 'Keep the password safe. Versara does not store it.', 'Save or share the protected PDF. Open it with a password-capable reader.'],
  metadata: ['Review the explanation of what will be removed.', 'Create a PDF without document metadata. Visible personal information is not redacted.', 'Review and save the result.'],
  flatten: ['Create image-based pages with visible annotations and form values baked in.', 'Text, links and forms become static. Keep your original if you need them.', 'Create, review and save the result.'],
  ocr: ['Choose the pages to recognize. OCR runs offline for English text.', 'Export text and review the preview for recognition errors.', 'Save or share the complete text file.'],
  extract_text: ['Choose the pages to export.', 'Export the existing text layer. For scanned pages, use Scan Text (OCR).', 'Review the preview, then save or share the full text file.'],
  repair: ['Choose a damaged PDF that can still be opened.', 'Attempt a native rewrite. The output is reopened and every page is validated.', 'Review the result before saving. Missing page content cannot be recovered.'],
  viewer: ['Open a PDF from Recents or choose one from Files.', 'Tap a page thumbnail below the preview. Pinch to zoom.', 'Tap Toolbox for editing tools, vertical scrolling or saving a copy.'],
  edit_text: ['Tap the text you want to change. Use Text list if it is hard to select.', 'Type your change and check the live preview. Tap Apply.', 'Tap Save, then Save / share to choose where to keep the copy.'],
  text: ['Tap the page where you want new text.', 'Type, choose the size and check the preview. Tap Add text.', 'Tap Save to create your edited copy.'],
  replace_text: ['Type the text to find and what to replace it with.', 'Tap Find in all pages and check the matches.', 'Tap Replace all, review the pages, then Save a new copy. Undo reverts the whole replacement.'],
  remove_text: ['Tap the text you want to remove.', 'Tap Delete selected text. Undo brings it back.', 'Save a new copy. Text deletion is not secure redaction.'],
  merge: ['Choose two or more PDFs.', 'Put the files in the order you want.', 'Tap Merge, check the result and save your copy.'],
  split: ['Choose the PDF you want to separate.', 'Choose individual pages, groups or a page range, such as 1-3.', 'Create the new PDFs, then open or save them.'],
  extract: ['Choose your PDF.', 'Select the pages to keep, such as 1, 3-5.', 'Create and save a new PDF with only those pages.'],
  delete: ['Choose your PDF.', 'Select the pages to remove. Check the remaining page count.', 'Create and save a new copy. Your original stays unchanged.'],
  reorder: ['Choose your PDF.', 'Move pages into the order you want.', 'Check the new order, then create and save your copy.'],
  rotate: ['Choose your PDF and select pages.', 'Choose which way to turn them.', 'Create the PDF, check the result and save it.'],
  from_image: ['Choose one or more images.', 'Arrange them and choose a page size.', 'Tap Save PDF, then open the result or check its saved folder.'],
};
