import type { ComponentProps } from 'react';
import type { UniversalIcon } from '@/components/universal-icon';

export type OptionIcon = Pick<ComponentProps<typeof UniversalIcon>, 'ios' | 'android'>;

// Keep icons stable across editors. Context-dependent choices can pass an explicit icon.
const icons = {
  undo: { ios: 'arrow.uturn.backward', android: 'undo' },
  redo: { ios: 'arrow.uturn.forward', android: 'redo' },
  reset: { ios: 'arrow.counterclockwise', android: 'restart-alt' },
  retry: { ios: 'arrow.clockwise', android: 'refresh' },
  close: { ios: 'xmark', android: 'close' },
  back: { ios: 'arrow.left', android: 'arrow-back' },
  save: { ios: 'square.and.arrow.down', android: 'save-alt' },
  share: { ios: 'square.and.arrow.up', android: 'share' },
  apply: { ios: 'checkmark', android: 'check' },
  open: { ios: 'arrow.up.forward.square', android: 'open-in-new' },
  browse: { ios: 'folder', android: 'folder-open' },
  preview: { ios: 'eye', android: 'visibility' },
  compare: { ios: 'rectangle.lefthalf.filled', android: 'compare' },
  delete: { ios: 'trash', android: 'delete-outline' },
  duplicate: { ios: 'square.on.square', android: 'content-copy' },
  add: { ios: 'plus', android: 'add' },
  subtract: { ios: 'minus', android: 'remove' },
  insert: { ios: 'doc.badge.plus', android: 'note-add' },
  document: { ios: 'doc', android: 'insert-drive-file' },
  pdf: { ios: 'doc.richtext', android: 'picture-as-pdf' },
  text: { ios: 'textformat', android: 'text-fields' },
  textFile: { ios: 'doc.text', android: 'description' },
  textList: { ios: 'list.bullet', android: 'format-list-bulleted' },
  earlier: { ios: 'chevron.left', android: 'chevron-left' },
  more: { ios: 'chevron.right', android: 'chevron-right' },
  select: { ios: 'cursorarrow', android: 'touch-app' },
  selectAll: { ios: 'checkmark.square', android: 'select-all' },
  deselect: { ios: 'square', android: 'deselect' },
  area: { ios: 'rectangle.dashed', android: 'select-all' },
  move: { ios: 'arrow.up.and.down.and.arrow.left.and.right', android: 'open-with' },
  reverse: { ios: 'arrow.up.arrow.down', android: 'swap-vert' },
  rotateLeft: { ios: 'rotate.left', android: 'rotate-left' },
  rotateRight: { ios: 'rotate.right', android: 'rotate-right' },
  flipHorizontal: { ios: 'arrow.left.and.right.righttriangle.left.righttriangle.right', android: 'flip' },
  flipVertical: { ios: 'arrow.up.and.down', android: 'swap-vert' },
  crop: { ios: 'crop', android: 'crop' },
  resize: { ios: 'arrow.up.left.and.arrow.down.right', android: 'photo-size-select-large' },
  percent: { ios: 'percent', android: 'percent' },
  pixels: { ios: 'ruler', android: 'straighten' },
  fit: { ios: 'arrow.down.right.and.arrow.up.left', android: 'fit-screen' },
  fill: { ios: 'arrow.up.left.and.arrow.down.right', android: 'crop' },
  stretch: { ios: 'arrow.left.and.right', android: 'aspect-ratio' },
  square: { ios: 'square', android: 'crop-square' },
  portrait: { ios: 'rectangle.portrait', android: 'crop-portrait' },
  landscape: { ios: 'rectangle', android: 'crop-landscape' },
  story: { ios: 'rectangle.portrait.on.rectangle.portrait', android: 'stay-current-portrait' },
  profile: { ios: 'person.crop.circle', android: 'account-circle' },
  pen: { ios: 'pencil.tip', android: 'draw' },
  pencil: { ios: 'pencil', android: 'edit' },
  marker: { ios: 'paintbrush.pointed', android: 'brush' },
  highlighter: { ios: 'highlighter', android: 'border-color' },
  brush: { ios: 'paintbrush', android: 'brush' },
  solid: { ios: 'line.diagonal', android: 'horizontal-rule' },
  dashed: { ios: 'rectangle.dashed', android: 'power-input' },
  dotted: { ios: 'ellipsis', android: 'more-horiz' },
  shapes: { ios: 'square.on.circle', android: 'category' },
  style: { ios: 'paintpalette', android: 'palette' },
  settings: { ios: 'gearshape', android: 'settings' },
  adjust: { ios: 'slider.horizontal.3', android: 'tune' },
  levels: { ios: 'chart.bar.xaxis', android: 'bar-chart' },
  curves: { ios: 'chart.xyaxis.line', android: 'show-chart' },
  none: { ios: 'circle.slash', android: 'block' },
  mono: { ios: 'circle.lefthalf.filled', android: 'filter-b-and-w' },
  sepia: { ios: 'camera.filters', android: 'filter-vintage' },
  vivid: { ios: 'sparkles', android: 'auto-awesome' },
  fade: { ios: 'drop.halffull', android: 'opacity' },
  cool: { ios: 'snowflake', android: 'ac-unit' },
  blacks: { ios: 'circle.fill', android: 'brightness-1' },
  shadows: { ios: 'moon.fill', android: 'brightness-2' },
  midtones: { ios: 'circle.lefthalf.filled', android: 'tonality' },
  highlights: { ios: 'sun.max', android: 'brightness-5' },
  whites: { ios: 'circle', android: 'panorama-fish-eye' },
  quality: { ios: 'sparkles', android: 'high-quality' },
  balanced: { ios: 'scalemass', android: 'balance' },
  compress: { ios: 'arrow.down.right.and.arrow.up.left', android: 'compress' },
  estimate: { ios: 'gauge.medium', android: 'speed' },
  merge: { ios: 'doc.on.doc', android: 'merge-type' },
  split: { ios: 'scissors', android: 'call-split' },
  pageGroups: { ios: 'square.stack', android: 'view-module' },
  ranges: { ios: 'list.number', android: 'format-list-numbered' },
  numbering: { ios: 'number', android: 'tag' },
  image: { ios: 'photo', android: 'image' },
  watermark: { ios: 'seal', android: 'branding-watermark' },
  repair: { ios: 'wrench.and.screwdriver', android: 'build' },
} satisfies Record<string, OptionIcon>;

type IconName = keyof typeof icons;

const choices: Readonly<Partial<Record<string, IconName>>> = {
  original: 'compare',
  'show changes': 'compare',
  none: 'none',
  free: 'crop',
  square: 'square',
  portrait: 'portrait',
  landscape: 'landscape',
  story: 'story',
  profile: 'profile',
  fit: 'fit',
  'fit image': 'fit',
  fill: 'fill',
  stretch: 'stretch',
  percentage: 'percent',
  pixels: 'pixels',
  mono: 'mono',
  sepia: 'sepia',
  vivid: 'vivid',
  fade: 'fade',
  cool: 'cool',
  pen: 'pen',
  pencil: 'pencil',
  marker: 'marker',
  highlighter: 'highlighter',
  brush: 'brush',
  solid: 'solid',
  dashed: 'dashed',
  dotted: 'dotted',
  shapes: 'shapes',
  select: 'select',
  'select & resize': 'move',
  'select all': 'selectAll',
  'clear selection': 'deselect',
  area: 'area',
  'select area': 'area',
  'reselect area': 'area',
  'whole image': 'image',
  'text only': 'text',
  'use text instead': 'text',
  'text file': 'textFile',
  'text list': 'textList',
  'earlier text': 'earlier',
  'more text': 'more',
  'use a blank page': 'document',
  'page groups': 'pageGroups',
  'every page': 'document',
  'custom ranges': 'ranges',
  'enter ranges': 'ranges',
  'max quality': 'quality',
  quality: 'quality',
  lossless: 'quality',
  balanced: 'balanced',
  smallest: 'compress',
  subtle: 'fade',
  bold: 'blacks',
  blacks: 'blacks',
  shadows: 'shadows',
  midtones: 'midtones',
  highlights: 'highlights',
  whites: 'whites',
  rgb: 'style',
  red: 'style',
  green: 'style',
  blue: 'style',
  levels: 'levels',
  curves: 'curves',
  style: 'style',
  settings: 'settings',
  'tool settings': 'settings',
  a4: 'document',
  letter: 'document',
  jpg: 'image',
  jpeg: 'image',
  png: 'image',
  tiff: 'image',
  webp: 'image',
  heic: 'image',
  heif: 'image',
  '1': 'numbering',
  'page 1': 'textFile',
  '1 of 10': 'ranges',
  '-': 'subtract',
  '+': 'add',
};

// Match the action first: "Open" must not match "pen", and "Save page order"
// must retain its save icon rather than being mistaken for page numbering.
const actions: readonly (readonly [RegExp, IconName])[] = [
  [/^undo\b/, 'undo'],
  [/^redo\b/, 'redo'],
  [/^reset\b/, 'reset'],
  [/^(retry|try again|run again)\b/, 'retry'],
  [/^(cancel|close|hide)\b/, 'close'],
  [/^(back|return)\b/, 'back'],
  [/^(delete|remove|discard)\b/, 'delete'],
  [/^duplicate\b/, 'duplicate'],
  [/^(save|export)\b/, 'save'],
  [/^share\b/, 'share'],
  [/^(apply|done|confirm|use)\b/, 'apply'],
  [/^open\b/, 'open'],
  [/^preview\b/, 'preview'],
  [/^compare\b/, 'compare'],
  [/^(browse|choose|change)\b/, 'browse'],
  [/^create\b.*\bpdf\b/, 'pdf'],
  [/^create\b/, 'add'],
  [/^insert\b/, 'insert'],
  [/^add\b/, 'add'],
  [/^merge\b/, 'merge'],
  [/^split\b/, 'split'],
  [/^reverse\b/, 'reverse'],
  [/^move\b/, 'move'],
  [/^(all )?(rotate )?left\b/, 'rotateLeft'],
  [/^(all )?(rotate )?right\b/, 'rotateRight'],
  [/^flip horizontal\b/, 'flipHorizontal'],
  [/^flip vertical\b/, 'flipVertical'],
  [/^select\b/, 'selectAll'],
  [/^(resize|size)\b/, 'resize'],
  [/^estimate\b/, 'estimate'],
  [/^compress\b/, 'compress'],
  [/^(attempt )?repair\b/, 'repair'],
  [/^(color|colour|style|format)\b/, 'style'],
  [/^(adjust|adjustments)\b/, 'adjust'],
  [/^(watermark|stamp)\b/, 'watermark'],
  [/^(draw|signature)\b/, 'pen'],
  [/^edit\b/, 'pencil'],
  [/^thinner\b/, 'subtract'],
  [/^thicker\b/, 'add'],
];

export function optionIcon(label: string): OptionIcon | undefined {
  const value = label.trim().toLowerCase();
  const choice = choices[value];
  if (choice) return icons[choice];
  if (/^\d+(\.\d+)?%$/.test(value)) return icons.percent;
  const ratio = /^(\d+):(\d+)$/.exec(value);
  if (ratio) {
    const width = Number(ratio[1]);
    const height = Number(ratio[2]);
    return width === height ? icons.square : width > height ? icons.landscape : icons.portrait;
  }
  const action = actions.find(([pattern]) => pattern.test(value));
  // Unrecognized labels remain readable without a misleading settings symbol.
  return action ? icons[action[1]] : undefined;
}
