plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.docengine'
version = '0.1.0'

android {
  namespace "expo.modules.docengine"
  defaultConfig {
    versionCode 1
    versionName "0.1.0"
    externalNativeBuild { cmake { cppFlags '-std=c++17 -fexceptions -frtti' } }
  }
  externalNativeBuild { cmake { path 'CMakeLists.txt'; version '3.22.1' } }
  sourceSets { main { assets.srcDirs += ['../fonts'] } }
  androidResources { noCompress 'ttf' }
  lintOptions { abortOnError false }
}
